//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6)
//
// On Tue Jun 30 14:31:31 EDT 2026
//
//
// Ports:
// Name                         I/O  size props
// get_binary_row                 O    64 reg
// RDY_get_binary_row             O     1 const
// get_decimal_row                O    64 reg
// RDY_get_decimal_row            O     1 const
// RDY_put_switches               O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// put_switches_1                 I     8
// EN_put_switches                I     1 inhigh
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkOledTop(
     CLK,
		 RST_N,
		 get_binary_row,
		 RDY_get_binary_row,
		 get_decimal_row,
		 RDY_get_decimal_row,
		 put_switches_1,
		 EN_put_switches,
		 RDY_put_switches);
  input  CLK;
  input  RST_N;

  // value method get_binary_row
  output [63 : 0] get_binary_row;
  output RDY_get_binary_row;

  // value method get_decimal_row
  output [63 : 0] get_decimal_row;
  output RDY_get_decimal_row;

  // action method put_switches
  input  [7 : 0] put_switches_1;
  input  EN_put_switches;
  output RDY_put_switches;

  // signals for module outputs
  wire [63 : 0] get_binary_row, get_decimal_row;
  wire RDY_get_binary_row, RDY_get_decimal_row, RDY_put_switches;

  // register bin_str_reg
  reg [63 : 0] bin_str_reg;
  wire [63 : 0] bin_str_reg$D_IN;
  wire bin_str_reg$EN;

  // register dec_str_reg
  reg [63 : 0] dec_str_reg;
  wire [63 : 0] dec_str_reg$D_IN;
  wire dec_str_reg$EN;

  // ports of submodule swVals
  wire [7 : 0] swVals$switchesSum_0_arg0;
  wire swVals$sw0,
       swVals$sw1,
       swVals$sw2,
       swVals$sw3,
       swVals$sw4,
       swVals$sw5,
       swVals$sw6,
       swVals$sw7;

  // remaining internal signals
  wire [7 : 0] swVals_switchesSum_0_arg0_QUOT_100___d22,
	       swVals_switchesSum_0_arg0_REM_100_5_QUOT_10___d26,
	       swVals_switchesSum_0_arg0_REM_100_5_REM_10___d28,
	       swVals_switchesSum_0_arg0_REM_100___d25;

  // value method get_binary_row
  assign get_binary_row = bin_str_reg ;
  assign RDY_get_binary_row = 1'd1 ;

  // value method get_decimal_row
  assign get_decimal_row = dec_str_reg ;
  assign RDY_get_decimal_row = 1'd1 ;

  // action method put_switches
  assign RDY_put_switches = 1'd1 ;

  // submodule swVals
  mkSwValsBetter swVals(.CLK(CLK),
			.RST_N(RST_N),
			.sw0(swVals$sw0),
			.sw1(swVals$sw1),
			.sw2(swVals$sw2),
			.sw3(swVals$sw3),
			.sw4(swVals$sw4),
			.sw5(swVals$sw5),
			.sw6(swVals$sw6),
			.sw7(swVals$sw7),
			.switchesSum_0_guard(),
			.switchesSum_0_arg0(swVals$switchesSum_0_arg0));

  // register bin_str_reg
  assign bin_str_reg$D_IN =
	     { swVals$switchesSum_0_arg0[7] ? 8'h31 : 8'h30,
	       swVals$switchesSum_0_arg0[6] ? 8'h31 : 8'h30,
	       swVals$switchesSum_0_arg0[5] ? 8'h31 : 8'h30,
	       swVals$switchesSum_0_arg0[4] ? 8'h31 : 8'h30,
	       swVals$switchesSum_0_arg0[3] ? 8'h31 : 8'h30,
	       swVals$switchesSum_0_arg0[2] ? 8'h31 : 8'h30,
	       swVals$switchesSum_0_arg0[1] ? 8'h31 : 8'h30,
	       swVals$switchesSum_0_arg0[0] ? 8'h31 : 8'h30 } ;
  assign bin_str_reg$EN = 1'd1 ;

  // register dec_str_reg
  assign dec_str_reg$D_IN =
	     { 40'h2020202020,
	       8'h30 + swVals_switchesSum_0_arg0_QUOT_100___d22,
	       8'h30 + swVals_switchesSum_0_arg0_REM_100_5_QUOT_10___d26,
	       8'h30 + swVals_switchesSum_0_arg0_REM_100_5_REM_10___d28 } ;
  assign dec_str_reg$EN = 1'd1 ;

  // submodule swVals
  assign swVals$sw0 = put_switches_1[0] ;
  assign swVals$sw1 = put_switches_1[1] ;
  assign swVals$sw2 = put_switches_1[2] ;
  assign swVals$sw3 = put_switches_1[3] ;
  assign swVals$sw4 = put_switches_1[4] ;
  assign swVals$sw5 = put_switches_1[5] ;
  assign swVals$sw6 = put_switches_1[6] ;
  assign swVals$sw7 = put_switches_1[7] ;

  // remaining internal signals
  assign swVals_switchesSum_0_arg0_QUOT_100___d22 =
	     swVals$switchesSum_0_arg0 / 8'd100 ;
  assign swVals_switchesSum_0_arg0_REM_100_5_QUOT_10___d26 =
	     swVals_switchesSum_0_arg0_REM_100___d25 / 8'd10 ;
  assign swVals_switchesSum_0_arg0_REM_100_5_REM_10___d28 =
	     swVals_switchesSum_0_arg0_REM_100___d25 % 8'd10 ;
  assign swVals_switchesSum_0_arg0_REM_100___d25 =
	     swVals$switchesSum_0_arg0 % 8'd100 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        bin_str_reg <= `BSV_ASSIGNMENT_DELAY 64'h2020202020202020;
	dec_str_reg <= `BSV_ASSIGNMENT_DELAY 64'h2020202020202020;
      end
    else
      begin
        if (bin_str_reg$EN)
	  bin_str_reg <= `BSV_ASSIGNMENT_DELAY bin_str_reg$D_IN;
	if (dec_str_reg$EN)
	  dec_str_reg <= `BSV_ASSIGNMENT_DELAY dec_str_reg$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    bin_str_reg = 64'hAAAAAAAAAAAAAAAA;
    dec_str_reg = 64'hAAAAAAAAAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkOledTop

