//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6)
//
// On Mon Jun 29 14:19:07 EDT 2026
//
//
// Ports:
// Name                         I/O  size props
// switchesSum_0_guard            O     1 const
// switchesSum_0_arg0             O     8
// CLK                            I     1 unused
// RST_N                          I     1 unused
// sw0                            I     1
// sw1                            I     1
// sw2                            I     1
// sw3                            I     1
// sw4                            I     1
// sw5                            I     1
// sw6                            I     1
// sw7                            I     1
//
// Combinational paths from inputs to outputs:
//   (sw0, sw1, sw2, sw3, sw4, sw5, sw6, sw7) -> switchesSum_0_arg0
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkSwValsBetter(
          CLK,
		      RST_N,
		      switchesSum_0_guard,
		      switchesSum_0_arg0,
		      
          sw0,
		      sw1,
		      sw2,
		      sw3,
		      sw4,
		      sw5,
		      sw6,
		      sw7);
          
  input  CLK;
  input  RST_N;

  // value method switchesSum_0_guard
  output switchesSum_0_guard;

  // value method switchesSum_0_arg0
  output [7 : 0] switchesSum_0_arg0;

  // action method sw0
  input  sw0;

  // action method sw1
  input  sw1;

  // action method sw2
  input  sw2;

  // action method sw3
  input  sw3;

  // action method sw4
  input  sw4;

  // action method sw5
  input  sw5;

  // action method sw6
  input  sw6;

  // action method sw7
  input  sw7;

  // signals for module outputs
  wire [7 : 0] switchesSum_0_arg0;
  wire switchesSum_0_guard;

  // remaining internal signals
  wire [7 : 0] IF_sw0_wire_wget_THEN_1_ELSE_0_PLUS_IF_sw1_wir_ETC___d14,
	       IF_sw0_wire_wget_THEN_1_ELSE_0_PLUS_IF_sw1_wir_ETC___d20,
	       IF_sw0_wire_wget_THEN_1_ELSE_0_PLUS_IF_sw1_wir_ETC___d8;

  // value method switchesSum_0_guard
  assign switchesSum_0_guard = 1'd1 ;

  // value method switchesSum_0_arg0
  assign switchesSum_0_arg0 =
	     IF_sw0_wire_wget_THEN_1_ELSE_0_PLUS_IF_sw1_wir_ETC___d20 +
	     (sw7 ? 8'd128 : 8'd0) ;

  // remaining internal signals
  assign IF_sw0_wire_wget_THEN_1_ELSE_0_PLUS_IF_sw1_wir_ETC___d14 =
	     IF_sw0_wire_wget_THEN_1_ELSE_0_PLUS_IF_sw1_wir_ETC___d8 +
	     (sw3 ? 8'd8 : 8'd0) +
	     (sw4 ? 8'd16 : 8'd0) ;
  assign IF_sw0_wire_wget_THEN_1_ELSE_0_PLUS_IF_sw1_wir_ETC___d20 =
	     IF_sw0_wire_wget_THEN_1_ELSE_0_PLUS_IF_sw1_wir_ETC___d14 +
	     (sw5 ? 8'd32 : 8'd0) +
	     (sw6 ? 8'd64 : 8'd0) ;
  assign IF_sw0_wire_wget_THEN_1_ELSE_0_PLUS_IF_sw1_wir_ETC___d8 =
	     (sw0 ? 8'd1 : 8'd0) + (sw1 ? 8'd2 : 8'd0) + (sw2 ? 8'd4 : 8'd0) ;
endmodule  // mkSwValsBetter

